### PR TITLE
Make posts editable and set layout similar to docs

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by johari9292 — COMMENTED** [review]
@abbasizaim Please can you use FlexDiv from react design system instead of Grid? It will be good as we are using FlexDiv all other components of our app
Also please try to use Trenary in place of if-else.
e,g. we can use **props?.post?  props.handleUpdate(props.post._id, values, markdownString):  props.handleSave(values, markdownString);**

 **if (props.post) {
        props.handleUpdate(props.post._id, values, markdownString);
      }
      else {
        props.handleSave(values, markdownString);
      }**

**Review by johari9292 — APPROVED** [review]

**Review by johari9292 — COMMENTED** [review]
@abbasizaim Please try to avoid extra div if we are required to use then sue React Fragment for better performance.
You can even use like this <>  <Comp1/> <Comp2/></>

**Review by johari9292 — APPROVED** [review]

**Comment by ghost** [comment]
Alright, will change the code

**Comment by ghost** [comment]
All good?

**Comment by johari9292** [comment]
> All good?

yeah, further  @BrendanWu  will review and merge to upstream master.

**Pull request merged**
